import { User } from '../schemas/userSchema'

export const usersData: User[] = [
    {
        name: 'John Doe',
        email: 'john.doe@example.com',
        phoneNumber: '987654321',
        dob: '1990-05-15',
        address: {
            city: 'Kathmandu',
            district: 'Kathmandu',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    {
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phoneNumber: '986543210',
        dob: '1985-12-28',
        address: {
            city: 'Pokhara',
            district: 'Kaski',
            province: '4',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/1.jpg',
    },
    {
        name: 'Michael Johnson',
        email: 'michael.johnson@example.com',
        phoneNumber: '985432109',
        dob: '1988-07-10',
        address: {
            city: 'Biratnagar',
            district: 'Morang',
            province: '1',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/2.jpg',
    },
    {
        name: 'Anna Williams',
        email: 'anna.williams@example.com',
        phoneNumber: '987654321',
        dob: '1990-05-15',
        address: {
            city: 'Kathmandu',
            district: 'Kathmandu',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/2.jpg',
    },
    {
        name: 'Emily Brown',
        email: 'emily.brown@example.com',
        phoneNumber: '986543210',
        dob: '1985-12-28',
        address: {
            city: 'Pokhara',
            district: 'Kaski',
            province: '4',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/3.jpg',
    },
    {
        name: 'Sophia Davis',
        email: 'sophia.davis@example.com',
        phoneNumber: '985432109',
        dob: '1988-07-10',
        address: {
            city: 'Biratnagar',
            district: 'Morang',
            province: '1',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/4.jpg',
    },
    {
        name: 'Daniel Taylor',
        email: 'daniel.taylor@example.com',
        phoneNumber: '984321098',
        dob: '1992-03-22',
        address: {
            city: 'Lalitpur',
            district: 'Lalitpur',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
    {
        name: 'Olivia Martinez',
        email: 'olivia.martinez@example.com',
        phoneNumber: '983210987',
        dob: '1987-09-16',
        address: {
            city: 'Bhaktapur',
            district: 'Bhaktapur',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/5.jpg',
    },
    {
        name: 'David Harris',
        email: 'david.harris@example.com',
        phoneNumber: '982109876',
        dob: '1986-11-08',
        address: {
            city: 'Dharan',
            district: 'Sunsari',
            province: '1',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/4.jpg',
    },
    {
        name: 'Ella Walker',
        email: 'ella.walker@example.com',
        phoneNumber: '981098765',
        dob: '1991-06-25',
        address: {
            city: 'Hetauda',
            district: 'Makwanpur',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/6.jpg',
    },
    {
        name: 'James Wilson',
        email: 'james.wilson@example.com',
        phoneNumber: '980987654',
        dob: '1989-08-19',
        address: {
            city: 'Janakpur',
            district: 'Dhanusha',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/5.jpg',
    },
    {
        name: 'Grace Lewis',
        email: 'grace.lewis@example.com',
        phoneNumber: '979876543',
        dob: '1984-01-12',
        address: {
            city: 'Chitwan',
            district: 'Chitwan',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/7.jpg',
    },
    {
        name: 'Henry Young',
        email: 'henry.young@example.com',
        phoneNumber: '978765432',
        dob: '1993-04-30',
        address: {
            city: 'Butwal',
            district: 'Rupandehi',
            province: '5',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/6.jpg',
    },
    {
        name: 'Isabella King',
        email: 'isabella.king@example.com',
        phoneNumber: '977654321',
        dob: '1982-02-21',
        address: {
            city: 'Nepalgunj',
            district: 'Banke',
            province: '5',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/8.jpg',
    },
    {
        name: 'Liam White',
        email: 'liam.white@example.com',
        phoneNumber: '976543210',
        dob: '1980-12-05',
        address: {
            city: 'Dhangadhi',
            district: 'Kailali',
            province: '7',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/7.jpg',
    },
    {
        name: 'Mia Hall',
        email: 'mia.hall@example.com',
        phoneNumber: '975432109',
        dob: '1995-11-18',
        address: {
            city: 'Birgunj',
            district: 'Parsa',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/9.jpg',
    },
    {
        name: 'Nathan Scott',
        email: 'nathan.scott@example.com',
        phoneNumber: '974321098',
        dob: '1983-07-03',
        address: {
            city: 'Ghorahi',
            district: 'Dang',
            province: '5',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/8.jpg',
    },
    {
        name: 'Ava Adams',
        email: 'ava.adams@example.com',
        phoneNumber: '973210987',
        dob: '1981-03-12',
        address: {
            city: 'Itahari',
            district: 'Sunsari',
            province: '1',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/10.jpg',
    },
    {
        name: 'William Campbell',
        email: 'william.campbell@example.com',
        phoneNumber: '972109876',
        dob: '1987-06-07',
        address: {
            city: 'Bharatpur',
            district: 'Chitwan',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/9.jpg',
    },
    {
        name: 'Chloe Turner',
        email: 'chloe.turner@example.com',
        phoneNumber: '971098765',
        dob: '1996-01-20',
        address: {
            city: 'Tulsipur',
            district: 'Dang',
            province: '5',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/11.jpg',
    },
    {
        name: 'Ethan Harris',
        email: 'ethan.harris@example.com',
        phoneNumber: '970987654',
        dob: '1985-09-15',
        address: {
            city: 'Dortmund',
            district: 'Germany',
            province: '1',
            country: 'Germany',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/10.jpg',
    },
    {
        name: 'Olivia Green',
        email: 'olivia.green@example.com',
        phoneNumber: '969876543',
        dob: '1992-08-02',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/12.jpg',
    },
    {
        name: 'Daniel Clark',
        email: 'daniel.clark@example.com',
        phoneNumber: '968765432',
        dob: '1988-04-29',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/11.jpg',
    },
    {
        name: 'Mr Black',
        email: 'black.wilson@example.com',
        phoneNumber: '967654321',
        dob: '1993-02-14',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/13.jpg',
    },
    {
        name: 'Panda Thompson',
        email: 'panda.thompson@example.com',
        phoneNumber: '966543210',
        dob: '1990-12-01',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/12.jpg',
    },
    {
        name: 'Suba Wilson',
        email: 'Suba.wilson@example.com',
        phoneNumber: '965432109',
        dob: '1993-02-14',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/14.jpg',
    },
    {
        name: 'Michael Obama',
        email: 'michael.obama@example.com',
        phoneNumber: '964321098',
        dob: '1990-12-01',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/13.jpg',
    },
    {
        name: 'Monte Wilson',
        email: 'monte.wilson@example.com',
        phoneNumber: '963210987',
        dob: '1993-02-14',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/15.jpg',
    },
    {
        name: 'Naveed Thompson',
        email: 'naveed.thompson@example.com',
        phoneNumber: '962109876',
        dob: '1990-12-01',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/14.jpg',
    },
    {
        name: 'Popa Wilson',
        email: 'popa.wilson@example.com',
        phoneNumber: '961098765',
        dob: '1993-02-14',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/16.jpg',
    },
    {
        name: 'John Sena',
        email: 'sena.john@example.com',
        phoneNumber: '960987654',
        dob: '1990-12-01',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/15.jpg',
    },
    {
        name: 'Sunj Wilson',
        email: 'sunj.wilson@example.com',
        phoneNumber: '959876543',
        dob: '1993-02-14',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/17.jpg',
    },
    {
        name: 'Pula Thompson',
        email: 'Pula.thompson@example.com',
        phoneNumber: '958765432',
        dob: '1990-12-01',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/16.jpg',
    },
    {
        name: 'Amanda Wilson',
        email: 'amanda.wilson@example.com',
        phoneNumber: '957654321',
        dob: '1993-02-14',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/18.jpg',
    },
    {
        name: 'Mout Thompson',
        email: 'mout.thompson@example.com',
        phoneNumber: '956543210',
        dob: '1990-12-01',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/17.jpg',
    },
    {
        name: 'White Wilson',
        email: 'white.wilson@example.com',
        phoneNumber: '955432109',
        dob: '1993-02-14',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/19.jpg',
    },
    {
        name: 'Kera Thompson',
        email: 'kera.thompson@example.com',
        phoneNumber: '954321098',
        dob: '1990-12-01',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/18.jpg',
    },
    {
        name: 'Jesse Pinkman',
        email: 'pinkman.wilson@example.com',
        phoneNumber: '953210987',
        dob: '1993-02-14',
        address: {
            city: 'Kathmandu',
            district: 'Bagmati',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/20.jpg',
    },
]
