import { User } from '../schemas/userSchema'

export const usersData: User[] = [
    {
        name: 'John Doe',
        email: 'john.doe@example.com',
        phoneNumber: '+977987654321',
        dob: '1990-05-15',
        address: {
            city: 'Kathmandu',
            district: 'Kathmandu',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    {
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phoneNumber: '+977986543210',
        dob: '1985-12-28',
        address: {
            city: 'Pokhara',
            district: 'Kaski',
            province: '4',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/1.jpg',
    },
    {
        name: 'Michael Johnson',
        email: 'michael.johnson@example.com',
        phoneNumber: '+977985432109',
        dob: '1988-07-10',
        address: {
            city: 'Biratnagar',
            district: 'Morang',
            province: '1',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/2.jpg',
    },
    {
        name: 'Anna Williams',
        email: 'anna.williams@example.com',
        phoneNumber: '+977987654321',
        dob: '1990-05-15',
        address: {
            city: 'Kathmandu',
            district: 'Kathmandu',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/2.jpg',
    },
    {
        name: 'Emily Brown',
        email: 'emily.brown@example.com',
        phoneNumber: '+977986543210',
        dob: '1985-12-28',
        address: {
            city: 'Pokhara',
            district: 'Kaski',
            province: '4',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/3.jpg',
    },
    {
        name: 'Sophia Davis',
        email: 'sophia.davis@example.com',
        phoneNumber: '+977985432109',
        dob: '1988-07-10',
        address: {
            city: 'Biratnagar',
            district: 'Morang',
            province: '1',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/4.jpg',
    },
    {
        name: 'Daniel Taylor',
        email: 'daniel.taylor@example.com',
        phoneNumber: '+977984321098',
        dob: '1992-03-22',
        address: {
            city: 'Lalitpur',
            district: 'Lalitpur',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
    {
        name: 'Olivia Martinez',
        email: 'olivia.martinez@example.com',
        phoneNumber: '+977983210987',
        dob: '1987-09-16',
        address: {
            city: 'Bhaktapur',
            district: 'Bhaktapur',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/5.jpg',
    },
    {
        name: 'David Harris',
        email: 'david.harris@example.com',
        phoneNumber: '+977982109876',
        dob: '1986-11-08',
        address: {
            city: 'Dharan',
            district: 'Sunsari',
            province: '1',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/4.jpg',
    },
    {
        name: 'Ella Walker',
        email: 'ella.walker@example.com',
        phoneNumber: '+977981098765',
        dob: '1991-06-25',
        address: {
            city: 'Hetauda',
            district: 'Makwanpur',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/6.jpg',
    },
    {
        name: 'James Wilson',
        email: 'james.wilson@example.com',
        phoneNumber: '+977980987654',
        dob: '1989-08-19',
        address: {
            city: 'Janakpur',
            district: 'Dhanusha',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/5.jpg',
    },
    {
        name: 'Grace Lewis',
        email: 'grace.lewis@example.com',
        phoneNumber: '+977979876543',
        dob: '1984-01-12',
        address: {
            city: 'Chitwan',
            district: 'Chitwan',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/7.jpg',
    },
    {
        name: 'Henry Young',
        email: 'henry.young@example.com',
        phoneNumber: '+977978765432',
        dob: '1993-04-30',
        address: {
            city: 'Butwal',
            district: 'Rupandehi',
            province: '5',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/6.jpg',
    },
    {
        name: 'Isabella King',
        email: 'isabella.king@example.com',
        phoneNumber: '+977977654321',
        dob: '1982-02-21',
        address: {
            city: 'Nepalgunj',
            district: 'Banke',
            province: '5',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/8.jpg',
    },
    {
        name: 'Liam White',
        email: 'liam.white@example.com',
        phoneNumber: '+977976543210',
        dob: '1980-12-05',
        address: {
            city: 'Dhangadhi',
            district: 'Kailali',
            province: '7',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/7.jpg',
    },
    {
        name: 'Mia Hall',
        email: 'mia.hall@example.com',
        phoneNumber: '+977975432109',
        dob: '1995-11-18',
        address: {
            city: 'Birgunj',
            district: 'Parsa',
            province: '2',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/9.jpg',
    },
    {
        name: 'Nathan Scott',
        email: 'nathan.scott@example.com',
        phoneNumber: '+977974321098',
        dob: '1983-07-03',
        address: {
            city: 'Ghorahi',
            district: 'Dang',
            province: '5',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/8.jpg',
    },
    {
        name: 'Ava Adams',
        email: 'ava.adams@example.com',
        phoneNumber: '+977973210987',
        dob: '1981-03-12',
        address: {
            city: 'Itahari',
            district: 'Sunsari',
            province: '1',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/10.jpg',
    },
    {
        name: 'William Campbell',
        email: 'william.campbell@example.com',
        phoneNumber: '+977972109876',
        dob: '1987-06-07',
        address: {
            city: 'Bharatpur',
            district: 'Chitwan',
            province: '3',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/men/9.jpg',
    },
    {
        name: 'Chloe Turner',
        email: 'chloe.turner@example.com',
        phoneNumber: '+977971098765',
        dob: '1996-01-20',
        address: {
            city: 'Tulsipur',
            district: 'Dang',
            province: '5',
            country: 'Nepal',
        },
        profilePicture: 'https://randomuser.me/api/portraits/women/11.jpg',
    },
]
