import { User } from '../schemas/userSchema'

export const usersData: User[] = [
    {
        name: 'John Doe',
        email: 'john.doe@example.com',
        phoneNumber: '+977987654321',
        dob: '1990-05-15',
        address: {
            city: 'Kathmandu',
            district: 'Kathmandu',
            province: 3,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/johndoe.jpg',
    },
    {
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phoneNumber: '+977986543210',
        dob: '1985-12-28',
        address: {
            city: 'Pokhara',
            district: 'Kaski',
            province: 4,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/janesmith.jpg',
    },
    {
        name: 'Michael Johnson',
        email: 'michael.johnson@example.com',
        phoneNumber: '+977985432109',
        dob: '1988-07-10',
        address: {
            city: 'Biratnagar',
            district: 'Morang',
            province: 1,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/michaeljohnson.jpg',
    },
    {
        name: 'Emily Brown',
        email: 'emily.brown@example.com',
        phoneNumber: '+977984321098',
        dob: '1995-03-20',
        address: {
            city: 'Birgunj',
            district: 'Parsa',
            province: 2,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/emilybrown.jpg',
    },
    {
        name: 'David Lee',
        email: 'david.lee@example.com',
        phoneNumber: '+977983210987',
        dob: '1983-09-05',
        address: {
            city: 'Butwal',
            district: 'Rupandehi',
            province: 5,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/davidlee.jpg',
    },
    {
        name: 'Sophia Wilson',
        email: 'sophia.wilson@example.com',
        phoneNumber: '+977982109876',
        dob: '1992-11-18',
        address: {
            city: 'Dharan',
            district: 'Sunsari',
            province: 1,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/sophiawilson.jpg',
    },
    {
        name: 'Daniel Martinez',
        email: 'daniel.martinez@example.com',
        phoneNumber: '+977981098765',
        dob: '1991-04-30',
        address: {
            city: 'Nepalgunj',
            district: 'Banke',
            province: 6,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/danielmartinez.jpg',
    },
    {
        name: 'Olivia Garcia',
        email: 'olivia.garcia@example.com',
        phoneNumber: '+977980987654',
        dob: '1987-06-25',
        address: {
            city: 'Itahari',
            district: 'Sunsari',
            province: 1,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/oliviagarcia.jpg',
    },
    {
        name: 'Matthew Taylor',
        email: 'matthew.taylor@example.com',
        phoneNumber: '+977989876543',
        dob: '1980-12-12',
        address: {
            city: 'Hetauda',
            district: 'Makwanpur',
            province: 3,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/matthewtaylor.jpg',
    },
    {
        name: 'Isabella Martinez',
        email: 'isabella.martinez@example.com',
        phoneNumber: '+977988765432',
        dob: '1989-08-08',
        address: {
            city: 'Dhangadhi',
            district: 'Kailali',
            province: 7,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/isabellamartinez.jpg',
    },
    {
        name: 'Alexander Hernandez',
        email: 'alexander.hernandez@example.com',
        phoneNumber: '+977987654321',
        dob: '1986-02-04',
        address: {
            city: 'Janakpur',
            district: 'Dhanusa',
            province: 2,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/alexanderhernandez.jpg',
    },
    {
        name: 'Emma Davis',
        email: 'emma.davis@example.com',
        phoneNumber: '+977986543210',
        dob: '1993-10-22',
        address: {
            city: 'Lalitpur',
            district: 'Lalitpur',
            province: 3,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/emmadavis.jpg',
    },
    {
        name: 'William Garcia',
        email: 'william.garcia@example.com',
        phoneNumber: '+977985432109',
        dob: '1984-04-14',
        address: {
            city: 'Kirtipur',
            district: 'Kathmandu',
            province: 3,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/williamgarcia.jpg',
    },
    {
        name: 'Ava Rodriguez',
        email: 'ava.rodriguez@example.com',
        phoneNumber: '+977984321098',
        dob: '1996-01-08',
        address: {
            city: 'Ghorahi',
            district: 'Dang',
            province: 5,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/avarodriguez.jpg',
    },
    {
        name: 'James Lopez',
        email: 'james.lopez@example.com',
        phoneNumber: '+977983210987',
        dob: '1982-07-30',
        address: {
            city: 'Tansen',
            district: 'Palpa',
            province: 5,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/jameslopez.jpg',
    },
    {
        name: 'Mia Moore',
        email: 'mia.moore@example.com',
        phoneNumber: '+977982109876',
        dob: '1990-09-16',
        address: {
            city: 'Dhankuta',
            district: 'Dhankuta',
            province: 1,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/miamoore.jpg',
    },
    {
        name: 'Benjamin Clark',
        email: 'benjamin.clark@example.com',
        phoneNumber: '+977981098765',
        dob: '1981-03-02',
        address: {
            city: 'Bhadrapur',
            district: 'Jhapa',
            province: 2,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/benjaminclark.jpg',
    },
    {
        name: 'Charlotte Hernandez',
        email: 'charlotte.hernandez@example.com',
        phoneNumber: '+977980987654',
        dob: '1988-11-25',
        address: {
            city: 'Ilam',
            district: 'Ilam',
            province: 1,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/charlottehernandez.jpg',
    },
    {
        name: 'Elijah White',
        email: 'elijah.white@example.com',
        phoneNumber: '+977989876543',
        dob: '1983-05-07',
        address: {
            city: 'Gulmi',
            district: 'Gulmi',
            province: 4,
            country: 'Nepal',
        },
        profilePicture: 'https://example.com/profiles/elijahwhite',
    },
]
